import type { ConfigType } from '../types/config.js';

export const defaultConfig: ConfigType = {
  // Default selection for API-based providers (v1.6+)
  defaults: {
    provider: 'ollama',
    model: 'llama3',
  },
  // API-based providers registry (used by providerService)
  providers: {
    ollama: {
      type: 'ollama',
      baseURL: 'http://localhost:11434',
    },
    openai: {
      type: 'openai-compatible',
      baseURL: 'https://api.openai.com/v1',
      apiKey: '',
    },
    claude: {
      type: 'openai-compatible',
      baseURL: 'https://api.anthropic.com/v1',
      apiKey: '',
    },
    gemini: {
      type: 'openai-compatible',
      baseURL: 'https://generativelanguage.googleapis.com/v1beta/openai',
      apiKey: '',
    },
    mistral: {
      type: 'openai-compatible',
      baseURL: 'https://api.mistral.ai/v1',
      apiKey: '',
    },
    openrouter: {
      type: 'openai-compatible',
      baseURL: 'https://openrouter.ai/api/v1',
      apiKey: '',
    },
    groq: {
      type: 'openai-compatible',
      baseURL: 'https://api.groq.com/openai/v1',
      apiKey: '',
    },
    together: {
      type: 'openai-compatible',
      baseURL: 'https://api.together.xyz/v1',
      apiKey: '',
    },
    deepseek: {
      type: 'openai-compatible',
      baseURL: 'https://api.deepseek.com/v1',
      apiKey: '',
    },
  },
  thresholds: {
    gate: 95,
    maxFileSizeMB: 5,
    maxTodoCount: 10,
    maxIndexLines: 300,
  },
  provider: {
    retry: {
      attempts: 3,
      delay: 1000, // ms
    },
  },
  security: {
    // Base forbidden patterns for project scanning
    forbidden: ['console.log(', 'print('],
    requiredRootDirs: ['src', '.sentineltm'],
    shell: {
      allowedCommands: [
        'ls',
        'dir',
        'cat',
        'type',
        'echo',
        'printenv',
        'env',
        'pwd',
        'cd',
        'mkdir',
        'touch',
        'head',
        'tail',
        'grep',
        'find',
        'which',
        'where',
        'ps',
        'top',
        'htop',
        'df',
        'du',
        'free',
        'uname',
        'hostname',
        'whoami',
        'id',
        'date',
        'time',
        'wc',
        'sort',
        'uniq',
        'cut',
        'paste',
        'join',
        'comm',
        'diff',
        'cmp',
        'strings',
        'file',
        'stat',
        'npm',
        'node',
        'git',
        'st',
        'python',
        'python3',
        'pip',
        'pip3',
        'tsc',
        'tsx',
        'deno',
        'bun',
        'cargo',
        'rustc',
        'go',
        'java',
        'javac',
        'dotnet',
      ],
      blockedCommands: [
        'rm',
        'rmdir',
        'del',
        'format',
        'fdisk',
        'mkfs',
        'dd',
        'mv',
        'cp',
        'ln',
        'chmod',
        'chown',
        'kill',
        'pkill',
        'killall',
        'reboot',
        'shutdown',
        'halt',
        'poweroff',
        'passwd',
        'su',
        'sudo',
        'useradd',
        'userdel',
        'groupadd',
        'groupdel',
        'mount',
        'umount',
        'swapon',
        'swapoff',
      ],
    },
  },
  i18n: {
    logs: 'en',
    chat: 'fa',
  },
  indexing: {
    include: ['**/*'],
    ignore: [
      'node_modules/**',
      'dist/**',
      '.git/**',
      '*.log',
      '*.lock',
      '.DS_Store',
      '.sentineltm/db/**',
    ],
  },
  meta: {
    gate: {
      lastRun: null,
    },
  } as Record<string, unknown>,
};
