export const defaultConfig = {
  defaults: {
    provider: 'qwen',
    model: 'qwen-coder-flash',
  },
  thresholds: {
    gate: 95,
    maxFileSizeMB: 5,
    maxTodoCount: 10,
    maxIndexLines: 300,
  },
  provider: {
    retry: {
      attempts: 3,
      delay: 1000, // ms
    },
  },
  security: {
    forbidden: ['console.log(', 'print(', 'eval' + '('],
    requiredRootDirs: ['src', '.sentineltm'],
    shell: {
      allowedCommands: [
        'ls',
        'dir',
        'cat',
        'type',
        'echo',
        'printenv',
        'env',
        'pwd',
        'cd',
        'mkdir',
        'touch',
        'head',
        'tail',
        'grep',
        'find',
        'which',
        'where',
        'ps',
        'top',
        'htop',
        'df',
        'du',
        'free',
        'uname',
        'hostname',
        'whoami',
        'id',
        'date',
        'time',
        'wc',
        'sort',
        'uniq',
        'cut',
        'paste',
        'join',
        'comm',
        'diff',
        'cmp',
        'strings',
        'file',
        'stat',
        'npm',
        'node',
        'git',
        'st',
        'python',
        'python3',
        'pip',
        'pip3',
        'tsc',
        'tsx',
        'deno',
        'bun',
        'cargo',
        'rustc',
        'go',
        'java',
        'javac',
        'dotnet',
      ],
      blockedCommands: [
        'rm',
        'rmdir',
        'del',
        'format',
        'fdisk',
        'mkfs',
        'dd',
        'mv',
        'cp',
        'ln',
        'chmod',
        'chown',
        'kill',
        'pkill',
        'killall',
        'reboot',
        'shutdown',
        'halt',
        'poweroff',
        'passwd',
        'su',
        'sudo',
        'useradd',
        'userdel',
        'groupadd',
        'groupdel',
        'mount',
        'umount',
        'swapon',
        'swapoff',
      ],
    },
  },
  i18n: {
    logs: 'en',
    chat: 'fa',
  },
  meta: {
    gate: {
      lastRun: null,
    },
  } as Record<string, unknown>,
};
